### ISSUE TITLE
may be a fix 

### ISSUE THREAD

**Issue by Allen3039** [nicejade/nicelinks-vue-client#2]
in this file jade-blog/src/assets/icons/index.js ,really need  this judgement `if (key === './index.js') return`? ,for the third parameter in `const files = require.context('.', true, /\.svg$/)` has filtered the result.

**Comment by nicejade** [comment]
Yeah, you're right, thanks. Here is a general wording, if it is such a context, it is not necessary to add this judgment. Modify later.

**Comment by nicejade** [comment]
@Allen3039  Yeah, you're right, thanks. Here is a general wording, if it is such a context, it is not necessary to add this judgment. Modify later.
