### ISSUE TITLE
切换语言的菜单

### ISSUE THREAD

**Issue by wanghaisheng** [nicejade/nicelinks-vue-client#25]
是不是可以放出来  摆在 登录注册的左边上

**Comment by nicejade** [comment]
@wanghaisheng 嗯，这是一个很棒的建议🙌。也是有这个打算（针对 PC 端），之是鉴于`语言切换`功能暂时还不够完善，就还没放出来；待后续优化之后，会这样做。十分感谢您的建议，诚恳的期待更多。

**Comment by wanghaisheng** [comment]
@nicejade 我体验了移动端 也就是在微信里打开链接  体验问题倒是不太大  左上角的菜单切换进去就能看到

**Comment by nicejade** [comment]
@wanghaisheng Okay, 非常感谢您的反馈🙌🙌（缺专业设计师斧正下）。
