### ISSUE TITLE
新链接输入框选择出现异常行为

### ISSUE THREAD

**Issue by deepkolos** [nicejade/nicelinks-vue-client#6]
位置: 
首页 -> 注入新链接链接

复现步骤:
0.选择文字的时候, 一直拖动选择到后面

效果图:
![bug0](https://user-images.githubusercontent.com/12824616/31530229-978dda14-b011-11e7-8fbb-d7bea0b3e172.gif)

**Comment by nicejade** [comment]
@deepkolos  非常感谢您的反馈。比较遗憾的是，再三看了效果图，并按照复现步骤去尝试重现，然而并没有发现什么异常；很大程度上，在于我没有理解您所传达的；可否烦请再次予以说明呢？再次感谢您的耐心和热心 😊 。

**Comment by deepkolos** [comment]
@nicejade 我的浏览器是世界之窗7 内核版本48 , 可能是我描述不正确吧, 我重新在 chrome 61测试了一遍也是有这个问题, 也重新录了Gif

在gif的行为是当选择到末尾 如果鼠标继续往后拖动, 会取消一部分选择, 然后再选回去

![bug0](https://user-images.githubusercontent.com/12824616/31539999-f47db0a2-b03c-11e7-8481-a7e96ccdcaaf.gif)

**Comment by deepkolos** [comment]
我也录了一个正常行为的input框

![normal0](https://user-images.githubusercontent.com/12824616/31540241-b83f6184-b03d-11e7-9c99-f309a991d12e.gif)

**Comment by nicejade** [comment]
@deepkolos Wow，这看起来可能是 `element-ui` 的一个未知性问题, 但还未找到证据来佐证这个猜测；之后升级 `element-ui` 到下一个稳定版本，再观测下这个问题。感谢你的耐心和付出。

**Comment by nicejade** [comment]
已将  `element-ui` 升级至最新版本。
